# Site settings
title: "Amit Bagaria - Resume"
description: "Resume for Amit Bagaria."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Amit Bagaria"
resume_title:                   "Fullstack Developer / Architect"
resume_contact_email:           "amit.bagaria@gmail.com"
resume_header_contact_info:     "A/304, RNA Regency Park CHS<br/>Maharashtra Nagar, Kandivali West<br/>Mumbai-400067, India"
resume_header_intro:            "A postgraduate in ‘Master in Computer Application’, having more than 15 years of experience in client server programming on JAVA/J2EE architecture and Asp.Net. As a quick learner and possessing a strong understanding capability, is capable of switching to any domain or functional area and skill set easily within a limited time frame. Basically a person with a very positive attitude and gives its best commitment towards the employer."

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_summary:         true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/cooldroid"
  resume_twitter_url:           "https://twitter.com/amitbagaria"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "https://facebook.com/amit.bagaria"
  resume_linkedin_url:          "https://www.linkedin.com/in/abagaria"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://www.amitbagaria.com"
  resume_pdf_url:               "https://github.com/cooldroid/cooldroid.github.io/releases/download/1.0.1/amitbagaria15_resume.pdf"

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
